/**
 * ============================================================================
 * NOTE.JS - Note Document Model
 * ============================================================================
 *
 * Defines the Note schema for storing user notes with rich content,
 * file attachments, and soft-delete functionality.
 *
 * SCHEMA OVERVIEW:
 * ----------------
 * - title: Note title (default: "Untitled")
 * - content: HTML content from Quill editor
 * - folder: Optional reference to organizing Folder
 * - user: Reference to owning User (required)
 * - attachments: Array of uploaded file metadata
 * - isDeleted: Soft-delete flag (false = active, true = in trash)
 * - deletedAt: Timestamp when moved to trash
 * - createdAt/updatedAt: Automatic timestamps
 *
 * SOFT DELETE PATTERN:
 * --------------------
 * Instead of permanently deleting notes, we use "soft delete":
 *
 * 1. User clicks delete → isDeleted = true, deletedAt = now
 * 2. Note appears in Trash view (isDeleted = true)
 * 3. User can restore → isDeleted = false, deletedAt = null
 * 4. Notes older than 30 days are auto-cleaned via cleanupOldDeletedNotes()
 *
 * Benefits:
 * - Accidental deletions can be recovered
 * - Provides "Trash" functionality like desktop apps
 * - Historical data preserved for a grace period
 *
 * ATTACHMENT STORAGE:
 * -------------------
 * Files are stored on disk in /server/uploads/ with UUID filenames.
 * The attachments array stores metadata, not the actual file content.
 *
 * File path: /uploads/{uuid}.{ext}
 * Metadata: { filename, originalName, mimetype, size, path }
 *
 * DATA RELATIONSHIPS:
 * -------------------
 *            ┌─────────────────┐
 *            │      User       │
 *            └────────┬────────┘
 *                     │ 1
 *                     │ owns
 *                     ▼ *
 *            ┌─────────────────┐      ┌─────────────────┐
 *            │      Note       │──────│     Folder      │
 *            │  (YOU ARE HERE) │ *  1 │   (optional)    │
 *            └────────┬────────┘      └─────────────────┘
 *                     │ 1
 *                     │ has
 *                     ▼ *
 *            ┌─────────────────┐
 *            │   Attachment    │
 *            │  (embedded)     │
 *            └─────────────────┘
 *
 * INDEXES:
 * --------
 * - (user, isDeleted): Efficient query for active/deleted notes
 * - (user, folder): Efficient query for notes in a folder
 * - deletedAt: For cleanup of old deleted notes
 *
 * RELATED FILES:
 * - ../models/User.js → Referenced via 'user' field
 * - ../models/Folder.js → Referenced via 'folder' field
 * - ../controllers/noteController.js → CRUD operations
 * - ../middleware/upload.js → Multer config for attachments
 * - ../routes/noteRoutes.js → API endpoints
 *
 * @module models/Note
 */

const mongoose = require('mongoose');

// ============================================================================
// ATTACHMENT SUB-SCHEMA
// ============================================================================

/**
 * Attachment Schema (Embedded Document)
 *
 * Stores metadata about uploaded files. The actual files are stored
 * on disk, not in MongoDB (binary data would bloat the database).
 *
 * Each attachment has its own _id for individual deletion.
 */
const attachmentSchema = new mongoose.Schema({
  /**
   * Stored filename - UUID generated by Multer
   * Example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890.jpg"
   */
  filename: String,

  /**
   * Original filename - What the user uploaded
   * Example: "vacation-photo.jpg"
   */
  originalName: String,

  /**
   * MIME type - File content type
   * Examples: "image/jpeg", "video/mp4"
   */
  mimetype: String,

  /**
   * File size in bytes
   * Used for display and validation
   */
  size: Number,

  /**
   * Storage path - URL path to access the file
   * Example: "/uploads/a1b2c3d4-e5f6-7890-abcd-ef1234567890.jpg"
   */
  path: String
}, {
  _id: true  // Generate _id for each attachment (allows individual deletion)
});

// ============================================================================
// NOTE SCHEMA
// ============================================================================

/**
 * Note Schema
 *
 * The core document for storing user notes with rich content.
 */
const noteSchema = new mongoose.Schema({
  /**
   * Note title - Displayed in note list and editor
   * Defaults to "Untitled" if not provided
   */
  title: {
    type: String,
    trim: true,
    maxlength: [200, 'Title cannot exceed 200 characters'],
    default: 'Untitled'
  },

  /**
   * Note content - HTML content for display and storage
   *
   * Content is always stored as HTML, regardless of editing mode:
   * - Normal mode: HTML from Quill rich text editor
   * - Markdown mode: HTML converted from Markdown via marked.js
   *
   * This unified format simplifies:
   * - Rendering in browser (direct HTML)
   * - Conversion to Markdown (for editing toggle)
   * - Search and preview generation
   *
   * Example: "<p>Hello <strong>world</strong></p>"
   */
  content: {
    type: String,
    default: ''
  },

  /**
   * Folder reference - Optional organization
   *
   * - null: Note is not in any folder (shows in "All Notes")
   * - ObjectId: Note belongs to specified folder
   *
   * When folder is deleted, this is set to null (not cascaded)
   */
  folder: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Folder',      // Reference to Folder model
    default: null       // Notes don't require a folder
  },

  /**
   * User reference - The note owner (required)
   *
   * Every note must belong to a user. This is used for:
   * - Ownership verification (security)
   * - Querying user's notes
   */
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  /**
   * Attachments array - Embedded file metadata
   *
   * Uses the attachmentSchema defined above.
   * Files are stored on disk, only metadata is in MongoDB.
   */
  attachments: [attachmentSchema],

  /**
   * Soft delete flag
   *
   * - false: Note is active (normal view)
   * - true: Note is in trash (trash view)
   */
  isDeleted: {
    type: Boolean,
    default: false
  },

  /**
   * Deletion timestamp
   *
   * Set when note is moved to trash.
   * Used for:
   * - Showing when note was deleted
   * - Auto-cleanup of notes older than 30 days
   */
  deletedAt: {
    type: Date,
    default: null
  }
}, {
  /**
   * Automatic Timestamps
   *
   * Mongoose automatically manages:
   * - createdAt: Set once when document is created
   * - updatedAt: Updated on every save
   */
  timestamps: true
});

// ============================================================================
// INDEXES
// ============================================================================

/**
 * Index: (user, isDeleted)
 *
 * Optimizes the most common query: getting active notes for a user
 * Query: Note.find({ user: userId, isDeleted: false })
 */
noteSchema.index({ user: 1, isDeleted: 1 });

/**
 * Index: (user, folder)
 *
 * Optimizes folder-filtered queries
 * Query: Note.find({ user: userId, folder: folderId })
 */
noteSchema.index({ user: 1, folder: 1 });

/**
 * Index: deletedAt
 *
 * Optimizes cleanup query for old deleted notes
 * Query: Note.deleteMany({ deletedAt: { $lt: thirtyDaysAgo } })
 */
noteSchema.index({ deletedAt: 1 });

// ============================================================================
// STATIC METHODS
// ============================================================================

/**
 * Cleanup Old Deleted Notes
 *
 * Permanently removes notes that have been in trash for over 30 days.
 * Called automatically when fetching trash (in noteController.getTrash).
 *
 * This implements the "auto-purge" feature of the trash:
 * - Notes in trash for < 30 days: Can be restored
 * - Notes in trash for > 30 days: Automatically deleted
 *
 * @static
 * @async
 * @returns {Promise<Object>} Mongoose deleteMany result with deletedCount
 *
 * @example
 * // In noteController.getTrash():
 * await Note.cleanupOldDeletedNotes();
 * const trashedNotes = await Note.find({ user: userId, isDeleted: true });
 */
noteSchema.statics.cleanupOldDeletedNotes = async function() {
  // Calculate date 30 days ago
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  // Delete all notes that are:
  // 1. Marked as deleted (isDeleted: true)
  // 2. Were deleted more than 30 days ago
  return this.deleteMany({
    isDeleted: true,
    deletedAt: { $lt: thirtyDaysAgo }
  });
};

// ============================================================================
// MODEL EXPORT
// ============================================================================

/**
 * Note Model
 *
 * Mongoose model for the 'notes' collection in MongoDB.
 *
 * Common queries:
 * - Active notes: Note.find({ user: userId, isDeleted: false })
 * - Trashed notes: Note.find({ user: userId, isDeleted: true })
 * - Notes in folder: Note.find({ user: userId, folder: folderId, isDeleted: false })
 * - Soft delete: Note.findByIdAndUpdate(id, { isDeleted: true, deletedAt: new Date() })
 * - Restore: Note.findByIdAndUpdate(id, { isDeleted: false, deletedAt: null })
 */
const Note = mongoose.model('Note', noteSchema);

module.exports = Note;
