/**
 * ============================================================================
 * USER.JS - User Account Model
 * ============================================================================
 *
 * Defines the User schema for storing user accounts with secure password hashing.
 * This is the foundation for authentication and data ownership in the application.
 *
 * SCHEMA OVERVIEW:
 * ----------------
 * - username: Unique display name (3-30 characters)
 * - email: Unique login identifier (lowercase, validated format)
 * - password: PBKDF2 hash (never stored in plain text)
 * - salt: Random bytes used in password hashing
 * - createdAt: Account creation timestamp
 *
 * SECURITY IMPLEMENTATION:
 * ------------------------
 * Password hashing uses PBKDF2 (Password-Based Key Derivation Function 2):
 * 1. Generate random 16-byte salt
 * 2. Hash password with salt using 1000 iterations of SHA-512
 * 3. Store both salt and hash (needed for verification)
 *
 * This prevents rainbow table attacks and ensures identical passwords
 * produce different hashes for different users.
 *
 * DATA RELATIONSHIPS:
 * -------------------
 * User ←──── Folder (user field references User._id)
 *   │
 *   └────── Note (user field references User._id)
 *
 * Each user owns their folders and notes. The user field is required
 * on both Folder and Note models for ownership verification.
 *
 * RELATED FILES:
 * - ../config/passport.js → Uses validPassword() for login
 * - ../controllers/authController.js → Uses setPassword() for registration
 * - ../models/Folder.js → References User via 'user' field
 * - ../models/Note.js → References User via 'user' field
 *
 * @module models/User
 */

const mongoose = require('mongoose');
const crypto = require('crypto');

// ============================================================================
// SCHEMA DEFINITION
// ============================================================================

/**
 * User Schema
 *
 * Defines the structure and validation rules for user documents.
 * Includes custom methods for password hashing and verification.
 */
const userSchema = new mongoose.Schema({
  /**
   * Username - Unique display name for the user
   * Used for identification in the UI (e.g., "Welcome, {username}")
   */
  username: {
    type: String,
    required: [true, 'Username is required'],
    unique: true,       // Enforced at database level (creates unique index)
    trim: true,         // Remove leading/trailing whitespace
    minlength: [3, 'Username must be at least 3 characters'],
    maxlength: [30, 'Username cannot exceed 30 characters']
  },

  /**
   * Email - Primary login identifier
   * Stored in lowercase for case-insensitive matching
   */
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,       // Prevents duplicate accounts
    lowercase: true,    // Automatically convert to lowercase
    trim: true,
    match: [/^\S+@\S+\.\S+$/, 'Please enter a valid email']  // Basic email format validation
  },

  /**
   * Password - PBKDF2 hash (NOT the plain text password)
   * Generated by setPassword() method
   */
  password: {
    type: String,
    required: [true, 'Password is required']
  },

  /**
   * Salt - Random bytes used for password hashing
   * Unique per user, stored alongside password hash
   */
  salt: {
    type: String,
    required: true
  },

  /**
   * Account creation timestamp
   * Automatically set when document is created
   */
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// ============================================================================
// INSTANCE METHODS
// ============================================================================

/**
 * Hash and Store Password
 *
 * Called during user registration to securely store the password.
 * Generates a random salt and creates a PBKDF2 hash.
 *
 * PBKDF2 Parameters:
 * - Iterations: 1000 (balance between security and performance)
 * - Key length: 64 bytes (512 bits)
 * - Digest: SHA-512
 *
 * @param {string} password - Plain text password from user input
 *
 * @example
 * const user = new User({ username: 'john', email: 'john@example.com' });
 * user.setPassword('mySecurePassword123');
 * await user.save();
 */
userSchema.methods.setPassword = function(password) {
  // Generate random 16-byte salt (32 hex characters)
  this.salt = crypto.randomBytes(16).toString('hex');

  // Create hash using PBKDF2
  // pbkdf2Sync(password, salt, iterations, keylen, digest)
  this.password = crypto.pbkdf2Sync(
    password,      // Plain text password
    this.salt,     // Random salt
    1000,          // Iterations
    64,            // Output key length in bytes
    'sha512'       // Hash algorithm
  ).toString('hex');
};

/**
 * Verify Password Against Stored Hash
 *
 * Called during login to check if the provided password matches.
 * Recreates the hash using the stored salt and compares.
 *
 * @param {string} password - Plain text password from login form
 * @returns {boolean} True if password matches, false otherwise
 *
 * @example
 * const user = await User.findOne({ email: 'john@example.com' });
 * if (user.validPassword('mySecurePassword123')) {
 *   // Login successful
 * }
 */
userSchema.methods.validPassword = function(password) {
  // Recreate hash with same parameters and stored salt
  const hash = crypto.pbkdf2Sync(
    password,
    this.salt,
    1000,
    64,
    'sha512'
  ).toString('hex');

  // Compare with stored hash (timing-safe comparison would be better)
  return this.password === hash;
};

/**
 * Sanitize User Object for JSON Response
 *
 * Removes sensitive fields (password, salt) when sending user data to client.
 * Called automatically when user object is serialized to JSON.
 *
 * @returns {Object} User object without sensitive fields
 *
 * @example
 * res.json({ user }); // Automatically calls toJSON(), excludes password/salt
 */
userSchema.methods.toJSON = function() {
  // Convert Mongoose document to plain object
  const obj = this.toObject();

  // Remove sensitive fields
  delete obj.password;
  delete obj.salt;

  return obj;
};

// ============================================================================
// MODEL EXPORT
// ============================================================================

/**
 * User Model
 *
 * Mongoose model for the 'users' collection in MongoDB.
 * Use this to create, query, update, and delete user documents.
 */
const User = mongoose.model('User', userSchema);

module.exports = User;
